apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: default
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=
  GF_SERVER_DOMAIN: bG9jYWxob3N0
  GF_SMTP_ENABLED: dHJ1ZQ==
  GF_SMTP_HOST: c210cC5nbWFpbC5jb206NTg3
  GF_SMTP_USER: c25nZXJtaXlhbm9nbHVAZ21haWwuY29t
  GF_SMTP_PASSWORD: eGx1eiBlcHd4IGNibWIgaHpjaw==
  GF_SMTP_SKIP_VERIFY: dHJ1ZQ==
  GF_SMTP_FROM_ADDRESS: c25nZXJtaXlhbm9nbHVAZ21haWwuY29t
