apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 120s
      evaluation_interval: 120s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - 'alertmanager-service.default.svc.cluster.local:9093'

    rule_files:
      - 'alerts_rules.yml'

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['prometheus-service.default.svc.cluster.local:9090']

      - job_name: 'Spring Boot Application input'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 2s
        static_configs:
          - targets: ['pdfcompare-service.default.svc.cluster.local:3333']
            labels:
              application: 'Pdf Compare'
